"""empty message

Revision ID: ad17315dd1b5
Revises: None
Create Date: 2015-12-29 15:27:43.365580

"""

# revision identifiers, used by Alembic.
revision = 'ad17315dd1b5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vacation_properties',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('image_url', sa.String(), nullable=False),
                    sa.Column('host_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reservations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('guest_id', sa.Integer(), nullable=True),
                    sa.Column('vacation_property_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['vacation_property_id'], ['vacation_properties.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('vacation_properties')
    op.drop_table('users')
    ### end Alembic commands ###
